# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: TitouCoch/PokeBagarre

on:
  push:
    branches:
      - main
      - tp3
      
permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm ci   # install packages
    - run: npm test # run tests (configured to use jest-junit reporter)

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: .\gradlew.bat test 
    - name: Run tests and build
      run: .\gradlew.bat build

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: reports/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results

